### ISSUE TITLE
Request for dsalgo

### ISSUE THREAD

**Issue by tidalu** [otabekswe/dsalgo#5]
Hi, are u planning to finish all topics soon, or will it stay as it is now , cuz i was going to use your dsalgo.uz for uzbek community

**Comment by otabekswe** [comment]
> Hi, are u planning to finish all topics soon, or will it stay as it is now , cuz i was going to use your dsalgo.uz for uzbek community

How much is your offer?

**Comment by otabekswe** [comment]
> well, i am not gonna offer anything actually, i saw that uncompleted but some well topics are well enough, so i asked if u are gonna update soon, or if it has been stopped on that status

then let's see what happens : )
